export default [
  {
    header: "Utama",
    description: "",
    child: [
      {
        title: "Dashboard",
        path: "/dashboard",
        icon: "ic:outline-dashboard",
        child: [],
        meta: {},
      },
      {
        title: "Carian",
        path: "/carian",
        icon: "ph:magnifying-glass",
        child: [],
        meta: {},
      },
      {
        title: "Laporan",
        path: "/laporan",
        icon: "ph:chart-bar-fill",
        child: [],
        meta: {},
      },
    ],
    meta: {},
  },
  {
    header: "Fungsi",
    description: "",
    child: [
      {
        title: "Komponen",
        icon: "ph:gear-fine",
        child: [
          {
            title: "Amaran",
            path: "/komponen/amaran",
            child: [],
            meta: {},
          },
          {
            title: "Butang",
            path: "/komponen/butang",
            child: [],
            meta: {},
          },
          {
            title: "Lencana",
            path: "/komponen/lencana",
            child: [],
            meta: {},
          },
          {
            title: "Collapse",
            path: "/komponen/collapse",
            child: [],
            meta: {},
          },
          {
            title: "Dropdown",
            path: "/komponen/dropdown",
            child: [],
            meta: {},
          },
          {
            title: "Modal",
            path: "/komponen/modal",
            child: [],
            meta: {},
          },
          {
            title: "Progress Bar",
            path: "/komponen/progress-bar",
            child: [],
            meta: {},
          },
          {
            title: "Tab",
            path: "/komponen/tab",
            child: [],
            meta: {},
          },
        ],
      },
      {
        title: "Datatable",
        path: "/datatable",
        icon: "ph:table",
        child: [],
        meta: {},
      },
      {
        title: "Borang",
        path: "/borang",
        icon: "ph:clipboard-text",
        child: [],
      },
      {
        title: "Ikon",
        path: "/ikon",
        icon: "iconamoon:slightly-smiling-face",
        child: [],
        meta: {},
      },
      {
        title: "Tipografi",
        path: "/tipografi",
        icon: "ph:text-aa",
        child: [],
        meta: {},
      },
      {
        title: "Senarai Mesej",
        path: "/senarai-mesej",
        icon: "ic:outline-mail",
        child: [],
        meta: {},
      },
    ],
    meta: {},
  },
];
